name: Consumer Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile

  trivy-scan:
    name: Config + Fs
    uses: lishsuki-maker/Week-4-Shared-Repo/.github/workflows/security-scan.yml@main
    with:
      severity: "CRITICAL,HIGH"

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - name: Generate an SBOM
        run: trivy image --format spdx-json --output sbom.json product-catalogue:2.0.0
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
